name: Update OHLC JSON

on:
  schedule:
    - cron: '* * * * *' # Setiap menit
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Wajib untuk Rebase

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install WS
        run: npm install ws

      - name: Run Script
        run: node olhc.js

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Fetch latest changes from remote FIRST
          git fetch origin main
          git rebase origin/main
          
          git add data.json
          
          # Hanya commit jika ada perubahan data
          if ! git diff --cached --exit-code; then
            git commit -m "Update OHLC: $(date)"
            git push origin main
          else
            echo "No changes detected."
          fi
