name: Update OHLC JSON

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install WS
        run: npm install ws

      - name: Run Script
        run: node olhc.js

      - name: Push Data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Tambahkan file
          git add data.json
          
          # Commit jika ada perubahan
          if ! git diff --cached --exit-code; then
            git commit -m "Update OHLC: $(date)"
            
            # Tarik perubahan terbaru dan gabungkan (Rebase)
            git pull origin main --rebase
            
            # Push ke main
            git push origin main
          else
            echo "No changes detected."
          fi
